services:
  plan2meet:
    build: .
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017/plan2meet
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
