name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag to push (e.g. v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: mrfenyx/plan2meet
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (custom tag)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag }}
            ${{ env.IMAGE_NAME }}:latest
